screen_size:
  - 1200
  - 700

fps: 72

background_number_of_layers: 4
background_number_of_stars: 80

ship_thrust: 400  # pixels per second per second
ship_rotation_increment: 5  # degrees per frame

movement_damping: 0.1

space_color: "#131424"
star_color: "#fffac9"
ship_color: "#ff0000"
fire_color: "#ffc864"

number_of_planets: 25


logging:
  # standard logging configuration
  version: 1
  disable_existing_loggers: True
  formatters:
    default: 
      format: '%(asctime)s %(levelname)s %(name)s - %(message)s'
    short:
      format: '%(levelname)s %(name)s - %(message)s'
    brief:
      format: '%(message)s'
  handlers: 
    stream:
      level: DEBUG
      formatter: brief
      class: logging.StreamHandler
      stream: ext://sys.stdout
    file:
      level: DEBUG
      formatter: default
      class: logging.FileHandler
      filename: ./output.log
      mode: w
  loggers:
    root:
      level: DEBUG
      handlers: 
        - stream
