screen_size:
  - 1200
  - 700

fps: 72
vsync: 1

background_number_of_layers: 4
background_number_of_stars: 120

colors:
  space: "#131424"
  stars: "#fffac9"
  fire: "#ffc864"
  glass_blue: "#1F2DBC"
  ship_red: "#D01D18"
  ship_green: "#00CF9A"
  ship_blue: "#0091CF"
  hud_red: "#db5941"

number_of_planets: 250

pilots:
  - pilot_name: "Cptn. Default"
    sprite_name_pattern: "ship_cd_\\d\\.png"
    ship_thrust: 400  # pixels per second per second
    ship_rotation_speed: 270  # degrees per second
    ship_movement_damping: 0.1
    ship_animation_frames: 2
    ship_fuel_consumption: 5
    ship_fuel_regeneration: 5
  - pilot_name: "Paul Arthritis"
    sprite_name_pattern: "ship_pa_\\d\\.png"
    ship_thrust: 200  # pixels per second per second
    ship_rotation_speed: 150  # degrees per second
    ship_movement_damping: 0.02
    ship_animation_frames: 3
    ship_fuel_consumption: 2
    ship_fuel_regeneration: 2
  - pilot_name: "Louise Cannon"
    sprite_name_pattern: "ship_lc_\\d\\.png"
    ship_thrust: 800  # pixels per second per second
    ship_rotation_speed: 310  # degrees per second
    ship_movement_damping: 0.15
    ship_animation_frames: 2
    ship_fuel_consumption: 9
    ship_fuel_regeneration: 5

logging:
  # standard logging configuration
  version: 1
  disable_existing_loggers: True
  formatters:
    default: 
      format: '%(asctime)s %(levelname)s %(name)s - %(message)s'
    short:
      format: '%(levelname)s %(name)s - %(message)s'
    brief:
      format: '%(message)s'
  handlers: 
    stream:
      level: DEBUG
      formatter: short
      class: logging.StreamHandler
      stream: ext://sys.stdout
    # file:
    #   level: DEBUG
    #   formatter: default
    #   class: logging.FileHandler
    #   filename: ./output.log
    #   mode: w
  loggers:
    BasePlanet:
      level: DEBUG
    ScrollingStarBackground:
      level: INFO
    root:
      level: DEBUG
      handlers: 
        - stream
